[package]
name = "core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
models = { path = "../models" }
db = { path = "../db" }
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }